[[redirects]]
  from = "/blog/*"
  to = "https://old.janabeck.com/blog/:splat"

[[redirects]]
  from = "/flatland*"
  to = "https://jebeck.github.io/flatland/"

[[redirects]]
  from = "/better-living-thru-components*"
  to = "https://jebeck.github.io/better-living-thru-components/"

[[redirects]]
  from = "/diving-bell-talk/codemania*"
  to = "https://jebeck.github.io/diving-bell-talk/codemania/"

[[redirects]]
  from = "/diving-bell-talk/nightly-build*"
  to = "https://jebeck.github.io/diving-bell-talk/nightly-build/"

[[redirects]]
  from = "/diving-bell-talk/*"
  to = "https://jebeck.github.io/diving-bell-talk/"

[[redirects]]
  from = "/javascript-therapy/fsto2017*"
  to ="https://jebeck.github.io/javascript-therapy/fsto2017/"

[[redirects]]
  from = "/javascript-therapy*"
  to ="https://jebeck.github.io/javascript-therapy/"